// Copyright (c) 2026 FlyByWire Simulations
// SPDX-License-Identifier: GPL-3.0

// Generated by tools/raas-voice/generate.py, do not edit.

import { RaasWord } from '@flybywiresim/fbw-sdk';

/** The length of each RAAS voice clip (sound/raas_<word in snake case>.wav), in seconds */
export const RAAS_CLIP_LENGTHS: Record<Exclude<RaasWord, 'pause'>, number> = {
  approaching: 0.593,
  runways: 0.678,
  onRunway: 0.705,
  zero: 0.521,
  one: 0.319,
  two: 0.417,
  three: 0.428,
  four: 0.408,
  five: 0.48,
  six: 0.554,
  seven: 0.528,
  eight: 0.361,
  nine: 0.35,
  left: 0.424,
  right: 0.411,
  center: 0.501,
  onTaxiway: 1,
  caution: 0.485,
  shortRunway: 0.867,
  taxiway: 0.722,
  thousand: 0.606,
  hundred: 0.43,
  thirty: 0.399,
  remaining: 0.502,
  available: 0.57,
};
