"""Generates the A32NX RAAS voice clips with the Piper text-to-speech engine.

The voice is Piper's en_US-ljspeech-medium, trained on the LJ Speech dataset, which is in the public domain.

Usage:
  python generate.py --piper <path to piper executable> --model <path to en_US-ljspeech-medium.onnx>

Writes one WAV file per word into the A32NX sound folder, and the clip table (L:var and length of each word)
used by the RAAS in the systems host.
"""

import argparse
import os
import re
import subprocess
import tempfile
import wave

import numpy as np

REPO = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', '..'))
SOUND_DIR = os.path.join(
    REPO, 'fbw-a32nx', 'src', 'base', 'flybywire-aircraft-a320-neo', 'SimObjects', 'AirPlanes', 'FlyByWire_A320_NEO',
    'sound')
CLIPS_TS = os.path.join(REPO, 'fbw-a32nx', 'src', 'systems', 'systems-host', 'systems', 'Raas', 'RaasClips.ts')

# The RAAS words (RaasWord in fbw-common/src/systems/shared/src/runway-awareness/Raas.ts) and what is said. A
# trailing comma keeps the voice up on the words that lead into more, a full stop brings it down on the last ones.
WORDS = {
    'approaching': 'Approaching,',
    'runways': 'runways.',
    'onRunway': 'On runway,',
    'zero': 'zero',
    'one': 'one',
    'two': 'two',
    'three': 'three',
    'four': 'four',
    'five': 'five',
    'six': 'six',
    'seven': 'seven',
    'eight': 'eight',
    'nine': 'nine',
    'left': 'left.',
    'right': 'right.',
    'center': 'center.',
    'onTaxiway': 'On taxiway!',
    'caution': 'Caution,',
    'shortRunway': 'short runway.',
    'taxiway': 'taxiway.',
    'thousand': 'thousand',
    'hundred': 'hundred',
    'thirty': 'thirty',
    'remaining': 'remaining.',
    'available': 'available.',
}

LENGTH_SCALE = '0.9'
PEAK_DBFS = -3.0
SILENCE_THRESHOLD = 0.02
FADE_S = 0.005
HIGH_PASS_HZ = 150


def snake(word: str) -> str:
    return re.sub(r'([A-Z])', r'_\1', word).lower()


def synthesize(piper: str, model: str, text: str, path: str) -> None:
    subprocess.run([piper, '-m', model, '-f', path, '--length_scale', LENGTH_SCALE, '-q'], input=text.encode(),
                   check=True, capture_output=True)


def read(path: str) -> tuple[np.ndarray, int]:
    with wave.open(path, 'rb') as w:
        rate = w.getframerate()
        data = np.frombuffer(w.readframes(w.getnframes()), dtype=np.int16).astype(np.float64) / 32768
    return data, rate


def process(data: np.ndarray, rate: int) -> np.ndarray:
    # High-pass (first order): the thin sound of a flight deck loudspeaker
    rc = 1 / (2 * np.pi * HIGH_PASS_HZ)
    alpha = rc / (rc + 1 / rate)
    out = np.empty_like(data)
    prev_x = prev_y = 0.0
    for i, x in enumerate(data):
        prev_y = alpha * (prev_y + x - prev_x)
        prev_x = x
        out[i] = prev_y
    # Trim the silence, fade in and out
    loud = np.nonzero(np.abs(out) > SILENCE_THRESHOLD * np.max(np.abs(out)))[0]
    out = out[max(0, loud[0] - int(0.01 * rate)):loud[-1] + int(0.02 * rate)]
    fade = int(FADE_S * rate)
    out[:fade] *= np.linspace(0, 1, fade)
    out[-fade:] *= np.linspace(1, 0, fade)
    return out / np.max(np.abs(out)) * 10 ** (PEAK_DBFS / 20)


def write(path: str, data: np.ndarray, rate: int) -> None:
    with wave.open(path, 'wb') as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(rate)
        w.writeframes((data * 32767).astype(np.int16).tobytes())


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument('--piper', required=True)
    parser.add_argument('--model', required=True)
    args = parser.parse_args()

    lengths = {}
    with tempfile.TemporaryDirectory() as tmp:
        for word, text in WORDS.items():
            raw = os.path.join(tmp, f'{word}.wav')
            synthesize(args.piper, args.model, text, raw)
            data, rate = read(raw)
            data = process(data, rate)
            write(os.path.join(SOUND_DIR, f'raas_{snake(word)}.wav'), data, rate)
            lengths[word] = len(data) / rate
            print(f'{word:12} {lengths[word]:.2f} s')

    lines = [
        '// Copyright (c) 2026 FlyByWire Simulations',
        '// SPDX-License-Identifier: GPL-3.0',
        '',
        '// Generated by tools/raas-voice/generate.py, do not edit.',
        '',
        "import { RaasWord } from '@flybywiresim/fbw-sdk';",
        '',
        '/** The length of each RAAS voice clip (sound/raas_<word in snake case>.wav), in seconds */',
        "export const RAAS_CLIP_LENGTHS: Record<Exclude<RaasWord, 'pause'>, number> = {",
        *[f'  {word}: {round(length, 3):g},' for word, length in lengths.items()],
        '};',
        '',
    ]
    with open(CLIPS_TS, 'w', newline='\n') as f:
        f.write('\n'.join(lines))


if __name__ == '__main__':
    main()
